name: Test Workflow
on:
 workflow_dispatch:
jobs:
 job1:
  name: Job 1
  runs-on: ubuntu-latest
  outputs:
   message: "Hi"
  steps:
    - name : This is step 1 in Job 1
      run : echo "Hello world from step1"
    - name : This is step 2 in Job 1
      run : echo "Hello world from step2"
 job2:
   name: Job 2
   runs-on: ubuntu-latest
   needs:
    - job1
   steps:
    - name : This is step 2 in Job 2
      run : echo "Final step"
 job3:
   name: Job 3
   runs-on: ubuntu-latest
   needs:
    - job1
   steps:
    - name : This is step 1 in Job 3
      run : echo "Final step 3"
 job4:
    name: Job 4
    runs-on: ubuntu-latest
    steps:
     - name : This is step 1 in Job 4
       run : echo "Final step 4"
    

